Вариант № 21
Решить методами Гаусса и Якоби, найти $\lambda_{min}$, $\lambda_{max}$, определить число обусловленности матрицы $\mu = ||A|| \cdot ||A^{-1}||$.
Сделать вывод нормы вектора невязки для обоих методов.

$$ 
\begin{cases}
    b_1 x_1 + c_1 x_2 = f_1 \\
    a_2 x_1 + b_2 x_2 + c_2 x_3 = f_2 \\
    a_3 x_2 + b_3 x_3 + c_3 x_4 = f_3 \\
    ... \\
    a_n x_{n-1} + b_n x_n + c_n x_{n + 1} = f_n \\
    p_1 x_1 + p_2 x_2 + \cdots + p_{n - 1} x_{n - 1} + p_n x_n + p_{n + 1} x_{n + 1} = f_{n + 1}
\end{cases}     $$

$$
n = 19, \ b_1 = 1, \ c_1 = 0, \ f_1 = 1, \\
a_i = c_i = 1, \ b_i = -2, \ p_i = 2, \ f_i = 2 / i^2, \ i = 2, 3,...,n, \\
f_{n + 1} = -n / 3, \ p_1 = p_{n + 1} = 1
$$

$$ A = 
\begin{pmatrix}
    1 & 0 & 0 & 0 & 0 & ... \\
    1 & -2 & 1 & 0 & 0 & ...\\
    0 & 1 & -2 & 1 & 0 & ...\\
    \cdots \\
    0 & \cdots & 0 & 1 & -2 & 1 \\
    1 & \cdots & 2 & 2 & 2  & 1  
\end{pmatrix}
$$
$$
F = 
\begin{pmatrix}
    1 \\
    1/2 \\
    2/9 \\
    \cdots \\
    2/19^2 \\
    -19/3 
\end{pmatrix}
$$

# Метод Гаусса


In [78]:
import numpy as np
%matplotlib inline

1. F-норма
$$||A||_F = \sqrt{ \sum_{i = 1}^m \sum_{j = 1}^n |A_{ij}|^2 } $$

2. Норма $L_1$
$$ ||A||_1 = \max \sum_{i = 1}^m |A_{ij}|^2, \quad j \in \overline{1, n} $$

2. Норма $L_\infty$
$$ ||A||_\infty = \max \sum_{j = 1}^n |A_{ij}|^2, \quad i \in \overline{1, m} $$

In [56]:
def F_norm(A):
    f_norm = 0
    
    for i in range(len(A)):
        for j in range(len(A[0])):
            f_norm += A[i][j]**2
    return f_norm

In [57]:
n = 19
slau_matrix = np.zeros((n+1, n+1))

slau_matrix[0][0] = 1
slau_matrix[n][0] = 1
slau_matrix[n][n] = 1

for i in range(1, n):
    slau_matrix[i][i] = -2
    slau_matrix[i][i - 1] = 1
    slau_matrix[i][i + 1] = 1
for i in range(1, n):
    slau_matrix[n][i] = 2

slau_matrix

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  

In [58]:
inv = np.linalg.inv(slau_matrix)
np.linalg.norm(slau_matrix), np.linalg.norm(inv), np.linalg.eig(slau_matrix)

(np.float64(13.527749258468683),
 np.float64(29.28666426708061),
 EigResult(eigenvalues=array([ 1.7963219 , -3.97272261, -3.89450294, -3.7589475 , -3.59033389,
        -3.35456314, -3.12333733, -2.80339085, -2.54944428, -2.16515869,
        -1.93766382, -0.10715371, -0.10836552, -0.40444485, -0.42171898,
        -1.50902903, -1.35380547, -0.83563561, -0.90610368,  1.        ]), eigenvectors=array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  4.47107229e-01],
        [ 1.33638527e-10, -5.34015367e-02,  1.03288663e-01,
          1.54417725e-01,  1.95330195e-01, -2.38700357e-01,
         -2.66198869e-01,  2.97116101e-01,  3.08516113e-01,
          3.23334705e-0

In [59]:
f_matrix = np.zeros((n+1, 1))

f_matrix[0] = 1
f_matrix[n] = 1

for i in range(1, n):
    f_matrix[i] = 2 / ((i + 1)**2)

f_matrix

array([[1.        ],
       [0.5       ],
       [0.22222222],
       [0.125     ],
       [0.08      ],
       [0.05555556],
       [0.04081633],
       [0.03125   ],
       [0.02469136],
       [0.02      ],
       [0.01652893],
       [0.01388889],
       [0.01183432],
       [0.01020408],
       [0.00888889],
       [0.0078125 ],
       [0.00692042],
       [0.00617284],
       [0.00554017],
       [1.        ]])

$$ \mu = ||A|| \cdot ||A^{-1}|| $$

In [60]:
mu = F_norm(slau_matrix) * F_norm(np.linalg.inv(slau_matrix))
print(f'Число обусловленности: {mu}')

Число обусловленности: 156960.69281236344


# QR-алгортим

## Классический процесс Грама — Шмидта
**Алгоритм**

Пусть имеются линейно независимые векторы $a_1, \dots , a_n$ и пусть \
$\text{proj}_b a$ — оператор проекции вектора $a$ на вектор $b$, определённый как
$$
\text{proj}_b a = \frac{(a , b)}{(b, b)} b
$$

где $(a, b)$ — скалярное произведение векторов $a$ и $b$.

Классический процесс Грама — Шмидта выполняется следующим образом:
$$
b_1 = a_1 \\
b_2 = a2 - \text{proj}_{b_1} a_2 \\
b_2 = a3 - \text{proj}_{b_1} a_3 - \text{proj}_{b_2} a_3 \\
\dots \\
b_n = a_n - \text{proj}_{b_1} a_n - \text{proj}_{b_2} a_n - \cdots - \text{proj}_{b_{n-1}} a_n
$$

На основе каждого вектора $b_j, j = 1...n$ может быть получен нормированный вектор $e_j$ единичной длины, определённый как
$$
e_j = \frac{b_j}{||b_j||} = \frac{b_j}{\sqrt{(b_j, b_j)}}
$$

Результаты процесса Грама — Шмидта:

$e_1 ,\dots , e_n$ - система ортонормированных векторов

In [62]:
def scalarMult(a, b):
    res = 0
    for i in range(len(a)):
        res += a[i] * b[i]
    return res

def proj(b, a):
    coef = scalarMult(a, b) / scalarMult(b, b)

    return  [coef * el for el in a]

In [63]:
def algGramSchmidt(a):
    vectors = [np.array(v, dtype=float) for v in a]
    orthogonal = []
    
    for v in vectors:
        u = v.copy()
        
        for w in orthogonal:
            # Проекция v на w
            proj = np.dot(v, w) / np.dot(w, w) * w
            u = u - proj
        
        if np.linalg.norm(u) > 1e-10:
            u = u / np.linalg.norm(u)
            orthogonal.append(u)
    
    return orthogonal

In [64]:
b = [1, 3, 4]
a = [2, 3, 1]
proj(b, a), scalarMult(a, b), scalarMult(b, b)

([1.1538461538461537, 1.7307692307692306, 0.5769230769230769], 15, 26)

In [65]:
a = [[1, 3, 4],
     [2, 3, 1],
     [4, 3, 3]]
algGramSchmidt(a)

[array([0.19611614, 0.58834841, 0.78446454]),
 array([ 0.61547108,  0.54893366, -0.56556802]),
 array([ 0.76337004, -0.59373225,  0.25445668])]

# QR-Разложение
Матрица $A$ размера $n \times m$, где $n \geq m$, с комплексными элементами может быть представлена в виде

   $$ A = QR $$
    

In [94]:
def qr_decomposition(A):
    vectors_column = []

    for i in range(len(A)):
        vectors_column.append([0]*len(A))
    print(len(vectors_column), len(vectors_column[0]))
    for i in range(len(A)):
        for j in range(len(A)):
            vectors_column[i][j] = A[j][i]
    
    e_vects = algGramSchmidt(vectors_column)

    Q = np.zeros((len(A), len(A)))

    for i in range(len(A)):
        for j in range(len(A)):
            Q[i][j] = e_vects[j][i]
    
    R = np.dot(np.linalg.matrix_transpose(Q), A)

    return Q, R
    

In [95]:
def qr_algorithm(A, num_iter, eps):
    T = A.copy()
    U = np.eye(A.shape[0])
    conv = [(T, U)]
    for i in range(num_iter):
        Q, R = qr_decomposition(T)
        T = R @ Q
        U = U @ Q
        conv.append((T, U))
        if np.sum(np.abs(np.tril(T, k=-1))) < eps:
            break
    return T, U, conv[1:]

In [ ]:
n = 7
A = np.random.randn(n, n)
# A = A.T @ A
A = A + A.T
true_eigvals, true_eigvec = np.linalg.eig(A)
print(true_eigvals)

[ 5.71309085  4.20074142 -4.96739523 -3.83639198 -0.82587463  0.90511585
  1.10551721]


In [106]:
T, U, conv = qr_algorithm(slau_matrix, 2000, 1e-6)
print(np.linalg.norm(slau_matrix - U @ T @ U.T))

20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 20
20 2

In [107]:
eigenvalues = np.diag(T)
eigenvalues

array([-3.97272259, -3.89450296, -3.7589475 , -3.59033389, -3.35456314,
       -3.12333733, -2.80339085, -2.54944428, -2.16515869, -1.93766382,
        1.7963219 , -1.50902903, -1.35380547,  1.        , -0.90610368,
       -0.83563561, -0.42171898, -0.40444485, -0.10836552, -0.10715371])

In [ ]:
lambdas = np.linalg.eigvals(slau_matrix)
print(f'Собственные чилсла(Numpy)\nМаксимальное собственное число матрицы: {max(lambdas)}\nМинимальное собственное число матрицы: {min(lambdas)}')
print(f'Собственные чилсла(QR-алгоритм)\nМаксимальное собственное число матрицы: {max(eigenvalues)}\nМинимальное собственное число матрицы: {min(eigenvalues)}')

Максимальное собственное число матрицы(библиотека): 1.796321903144047
Минимальное собственное число матрицы: -3.97272260680545
Максимальное собственное число матрицы(QR): 1.7963219031430502
Минимальное собственное число матрицы: -3.9727225884052295


In [108]:
def getDiscrepancyVector(A, X, F):
    return np.dot(A, X) - F

In [ ]:
def MethodGaussa(A_matrix, F_matrix):
    A = A_matrix.copy()
    F = F_matrix.copy()
    
    for i in range(len(A)):
        for j in range(i + 1, len(A)):
            coef = A[j][i] / A[i][i]
            for k in range(len(A)):
                A[j][k] -= A[i][k] * coef
            F[j] -= F[i] * coef
                
    X = np.zeros((len(A), 1))
    
    for i in range(len(A) - 1, -1, -1):
        x_sum = F[i]
        for j in range(i, len(A)):
            x_sum -= A[i][j] * X[j]
        X[i] = x_sum / A[i][i]
    
    r = getDiscrepancyVector(A_matrix, X, F_matrix)
    print(r)
    
    return X

In [ ]:
np.linalg.solve(slau_matrix, f_matrix)

array([[ 1.        ],
       [ 0.04678276],
       [-0.40643447],
       [-0.63742949],
       [-0.7434245 ],
       [-0.76941952],
       [-0.73985898],
       [-0.66948211],
       [-0.56785524],
       [-0.44153702],
       [-0.29521879],
       [-0.13237164],
       [ 0.0443644 ],
       [ 0.23293476],
       [ 0.4317092 ],
       [ 0.63937253],
       [ 0.85484836],
       [ 1.0772446 ],
       [ 1.30581369],
       [ 1.53992294]])

In [ ]:
MethodGaussa(slau_matrix, f_matrix)

[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 6.93889390e-17]
 [ 2.77555756e-17]
 [ 4.85722573e-17]
 [ 0.00000000e+00]
 [-1.11022302e-16]
 [ 1.73472348e-17]
 [-5.55111512e-17]
 [ 1.17961196e-16]
 [-8.67361738e-18]
 [ 6.76542156e-17]
 [-5.37764278e-17]
 [ 0.00000000e+00]
 [ 1.05818132e-16]
 [ 2.77555756e-17]
 [-5.29090660e-17]
 [-1.55431223e-15]]


array([[ 1.        ],
       [ 0.04678276],
       [-0.40643447],
       [-0.63742949],
       [-0.7434245 ],
       [-0.76941952],
       [-0.73985898],
       [-0.66948211],
       [-0.56785524],
       [-0.44153702],
       [-0.29521879],
       [-0.13237164],
       [ 0.0443644 ],
       [ 0.23293476],
       [ 0.4317092 ],
       [ 0.63937253],
       [ 0.85484836],
       [ 1.0772446 ],
       [ 1.30581369],
       [ 1.53992294]])

In [ ]:
def MethodJacobiGauss(A_matrix, F_matrix, Eps=0.001):
    A = A_matrix.copy()
    F = F_matrix.copy()
    n = len(A)

    L = np.zeros((n, n))
    D = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        for j in range(i):
            L[i][j] = A[i][j]
    for i in range(n):
        D[i][i] = A[i][i]
        
    for i in range(n):
        for j in range(i + 1, n):
            U[i][j] = A[i][j]

    R = np.dot(-1 * np.linalg.inv(D), L + U)
    F_vect = np.dot(np.linalg.inv(D), F)

    X = np.zeros((n, 1))
    X_next = np.dot(R, X) + F_vect
    
    r = getDiscrepancyVector(A, X_next, F) # вектор невязки
    
    # Eps = 0.001
    while max(r) > Eps:
        X = X_next
        X_next = np.dot(R, X) + F_vect
        
        r = getDiscrepancyVector(A, X_next, F)
        # print(r)
    r = getDiscrepancyVector(A, X_next, F)
    print(r)
    return X
    

In [ ]:
MethodJacobiGauss(slau_matrix, f_matrix)

[[ 0.00000000e+00]
 [ 1.62837682e-04]
 [-3.23956384e-04]
 [ 4.71052122e-04]
 [-6.12400778e-04]
 [ 7.28704919e-04]
 [-8.33828805e-04]
 [ 9.07988366e-04]
 [-9.64254903e-04]
 [ 9.89356892e-04]
 [-9.89808566e-04]
 [ 9.63688913e-04]
 [-9.08135074e-04]
 [ 8.33391111e-04]
 [-7.28488425e-04]
 [ 6.12281915e-04]
 [-4.70569533e-04]
 [ 3.24211828e-04]
 [-1.62297895e-04]
 [-2.62178988e-07]]


array([[ 1.        ],
       [ 0.04683184],
       [-0.40650286],
       [-0.63728967],
       [-0.74355785],
       [-0.76920959],
       [-0.74004922],
       [-0.66923153],
       [-0.56808807],
       [-0.44127826],
       [-0.29547273],
       [-0.13213456],
       [ 0.04411717],
       [ 0.23312687],
       [ 0.43149972],
       [ 0.63950458],
       [ 0.85470591],
       [ 1.07730909],
       [ 1.30576001],
       [ 1.53991808]])